<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>ApoVolume</AssemblyName>
    <Version>1.6.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ApoVolume.Core\ApoVolume.Core.csproj" />
  </ItemGroup>
</Project>
